version: "3"
services:
  postgres:
    image: registry.test.work/postgres:14.1
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - ./src/utils/datastore/postgresql/data:/var/lib/postgresql/data/
      - ./src/utils/datastore/postgresql-initdb.d:/docker-entrypoint-initdb.d
      - ./src/utils/datastore/postgresql/backups:/db-backups/
  tg_parser_node:
    image: sampleNode
    ports:
      - 3001:3001
